name: Test

on:
  push:
    branches:
      - master
      - ghworkflow
  pull_request:
    branches:
      - master

jobs:

  linux:
    name: go-linux
    strategy:
      matrix:
        go: [ "1.23", "1.24" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./...
      - run: go vet ./...

  linux-32bit:
    name: go-linux-32bit
    strategy:
      matrix:
        go: [ "1.23", "1.24" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./...

  darwin:
    name: go-macos
    strategy:
      matrix:
        go: [ "1.23", "1.24" ]
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./...

  linux-stress:
    name: go-linux-stress
    strategy:
      matrix:
        go: [ "1.23", "1.24" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go install github.com/cockroachdb/stress@latest
      - run: go test ./... -exec 'stress -p 2 -maxruns 100' -v

  linux-stress-race:
    name: go-linux-stress-race
    strategy:
      matrix:
        go: [ "1.23", "1.24" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go install github.com/cockroachdb/stress@latest
      - run: go test ./... -race -exec 'stress -p 1 -maxruns 20' -v
